server:
  port: 8090
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8111
          predicates:
            - Path=/api/**
#          filters:
#            - AddRequestHeader=xunhao, awag
#            - AddRequestParameter=name, dog
#            - name: CircuitBreaker #jiangji
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/fallback
#        - id: xunhao-fallback
#          uri: https://
#          predicates:
#            -Path=/fallback

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: 23333
  registry:
    id: nacos-registry
    address: nacos://localhost:8848